### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ServerBSvvv** [SB-9838/cpp-brawl#1]
script encrypted?

**Comment by SB-9838** [comment]
compiled* and yes, 

this is an open-sources server and not an open-source client.

**Comment by ServerBSvvv** [comment]
and this repository includes instructions on how to make a dump of libg.so?)

**Comment by SB-9838** [comment]
a
no?
it's jsut a cpp server base

**Comment by moonbrawl** [comment]
а зачем тебе чистый скрипт, у тебя же был ник HACKERBSVVV

**Comment by ServerBSvvv** [comment]
а у тебя был ник DUDKABRAWLMAKER
