### ISSUE TITLE
в опын бравле есть анлаин и он на c# лучше чем тваё гавно без анлаина

### ISSUE THREAD

**Issue by crceck123** [SB-9838/cpp-brawl#2]

**Comment by ServerBSvvv** [comment]
но это эксклюзив! c++!

**Comment by TheAcelot** [comment]
c++ легко, или ты не умеешь кодить??

> но это эксклюзив! c++!

**Comment by ServerBSvvv** [comment]
> c++ легко, или ты не умеешь кодить??
> 
> > но это эксклюзив! c++!

для меня пайтон, это всё!

**Comment by TheAcelot** [comment]
> > c++ легко, или ты не умеешь кодить??
> > > но это эксклюзив! c++!
> 
> для меня пайтон, это всё!

лох

**Comment by SB-9838** [comment]
this isn't a place to chat and I clearly said everything should only be discussed in the discord server
also idc for open brawl lol
