### ISSUE TITLE
sb9838 dudniks techhhhh

### ISSUE THREAD

**Issue by moonbrawl** [SB-9838/cpp-brawl#3]
ну чё это такое, байтстрим хуже чем в классике, у оцекока даже лучше говнокод вышел чем тут
![image](https://user-images.githubusercontent.com/100240269/160294344-3413a5ab-f66c-40f4-961e-7985ce9d33cd.png)

**Comment by ServerBSvvv** [comment]
но это эксклюзив! c++!

**Comment by moonbrawl** [comment]
и чё

**Comment by TheAcelot** [comment]
> но это эксклюзив! c++!

так серв на с++ легко делается

**Comment by SB-9838** [comment]
nice moonbrawl, the private server that have vip to max brawlers.
is this nulls 2.0 worst edition?

**Comment by moonbrawl** [comment]
у меня хоть сервер лучше и стабильнее твоего говна, спокойно тянет 400+ игроков

**Comment by moonbrawl** [comment]
![image](https://user-images.githubusercontent.com/100240269/160294529-c09248b9-c836-4a9f-a7e0-0de28e6bf486.png)

**Comment by ServerBSvvv** [comment]
так а ты тоже

**Comment by moonbrawl** [comment]
пруф

**Comment by ServerBSvvv** [comment]
посмотри в зеркало, увидешь пруф
